
services:
  api:
    build: .
    image: dbwalker/lorawan-fieldtest:latest
    container_name: tracker-api
    depends_on:
      - db
    ports:
      - "17560:17560"
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/yourdb
    env_file:
      - .env

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "{API_PORT}:443"
    volumes:
      - ./templates:/etc/nginx/templates:ro
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - api
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
