
services:
  api:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    image: dbwalker/lorawan-fieldtest:latest
    container_name: tracker-api
    depends_on:
      - db
    ports:
      - "17560:17560"
    # expose port 8080 for Swagger API documentation
    expose:
      - "8080"
    env_file:
      - .env

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "${API_PORT:-443}:443"
    volumes:
      - ./templates:/etc/nginx/templates:ro
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - api
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dynamic_data/db:/var/lib/postgresql/data

  appsmith:
    image: appsmith/appsmith-ce
    expose:
      - "80"
    volumes:
      - ./dynamic_data/appsmith:/appsmith-stacks

